Repository DDD-Community/DDD-9-ANSAYO-ANDROID, pull requests merged in 2023-08, with the labels that each got.

#26 [ feature ] : 코스 작성시 장소 검색 및 추가 - App layer
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceActivity.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceAdapter.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceBindingAdapter.kt
  app/src/main/res/layout/activity_search_add_place.xml
  app/src/main/res/layout/item_search_add_place.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  core-design/src/main/java/com/ddd/ansayo/core_design/DividerDecoration.kt
  core-design/src/main/res/drawable/divider.xml
  core-design/src/main/res/drawable/ic_star_gray.xml
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/model/AddPlaceInfoDto.kt
Labels: 기능개발

#27 [ feature ] : 코스 작성시 장소 검색 및 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceActivity.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceAdapter.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceBindingAdapter.kt
  app/src/main/res/layout/activity_search_add_place.xml
  app/src/main/res/layout/item_search_add_place.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  core-design/src/main/java/com/ddd/ansayo/core_design/DividerDecoration.kt
  core-design/src/main/res/drawable/divider.xml
  core-design/src/main/res/drawable/ic_star_gray.xml
  core-model/build.gradle.kts
  core-model/src/main/java/com/ddd/ansayo/core_model/place/Place.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/PlaceGeometry.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/PlacePhoto.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/di/RepositoryModule.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/place/SearchAddPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/SearchAddPlaceAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/SearchAddPlaceMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/SearchAddPlaceState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/place/GetPlacesUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/model/AddPlaceInfoDto.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/place/SearchAddPlaceViewModel.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/ServiceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#28 [ feature ] : 이미지 확대 보기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/image/ImageViewerActivity.kt
  app/src/main/java/com/ddd/ansayo/image/ImageViewerAdapter.kt
  app/src/main/res/layout/activity_image_viewer.xml
  app/src/main/res/layout/item_image_viewer.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable/ic_back.xml
  core-design/src/main/res/drawable/shadow_image_viewer.xml
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
Labels: 기능개발

#33 [ feature ] : 메인화면 구조 설계
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/MainActivity.kt
  app/src/main/java/com/ddd/ansayo/base/BaseFragment.kt
  app/src/main/java/com/ddd/ansayo/main/MainActivity.kt
  app/src/main/java/com/ddd/ansayo/main/MainFragmentAdapter.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteListFragment.kt
  app/src/main/java/com/ddd/ansayo/main/home/HomeFragment.kt
  app/src/main/java/com/ddd/ansayo/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ddd/ansayo/main/record/MyRecordFragment.kt
  app/src/main/res/layout/activity_image_viewer.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_favorite_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_record.xml
  app/src/main/res/menu/main_bottom_navigation_items.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable/ic_navi_home_default.xml
  core-design/src/main/res/drawable/ic_navi_home_sel.xml
  core-design/src/main/res/drawable/ic_navi_like_default.xml
  core-design/src/main/res/drawable/ic_navi_like_sel.xml
  core-design/src/main/res/drawable/ic_navi_mypage_default.xml
  core-design/src/main/res/drawable/ic_navi_mypage_sel.xml
  core-design/src/main/res/drawable/ic_navi_myrecord_default.xml
  core-design/src/main/res/drawable/ic_navi_myrecord_sel.xml
  core-design/src/main/res/drawable/selector_navi_favorite.xml
  core-design/src/main/res/drawable/selector_navi_home.xml
  core-design/src/main/res/drawable/selector_navi_my_page.xml
  core-design/src/main/res/drawable/selector_navi_my_record.xml
Labels: 기능개발

#36 [ feature ] : 작성한 코스
  app/src/main/java/com/ddd/ansayo/common/CourseViewHolder.kt
  app/src/main/java/com/ddd/ansayo/course/CourseCreateActivity.kt
  app/src/main/java/com/ddd/ansayo/main/MainActivity.kt
  app/src/main/java/com/ddd/ansayo/main/record/MyRecordAdapter.kt
  app/src/main/java/com/ddd/ansayo/main/record/MyRecordFragment.kt
  app/src/main/res/layout/fragment_my_record.xml
  app/src/main/res/layout/item_course.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable/ic_place.xml
  core-design/src/main/res/drawable/ic_write.xml
  core-design/src/main/res/drawable/img_no_my_record.xml
  domain/src/main/java/com/ddd/ansayo/domain/handler/record/MyRecordMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/Course.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/record/MyRecordAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/record/MyRecordMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/record/MyRecordState.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/record/MyRecordViewModel.kt
Labels: 기능개발

#40 [ refactor ] : drawable 정리
  core-design/src/main/java/com/ddd/ansayo/core_design/util/dialog/BadgeDialog.kt
  core-design/src/main/res/drawable/btn_edit_badge.png
  core-design/src/main/res/drawable/btn_map_back.png
  core-design/src/main/res/drawable/btn_map_more.png
  core-design/src/main/res/drawable/ic_arrow_orange_16.png
  core-design/src/main/res/drawable/ic_back_32.png
  core-design/src/main/res/drawable/ic_back_w_32.png
  core-design/src/main/res/drawable/ic_badge_check.xml
  core-design/src/main/res/drawable/ic_badge_info_arrow.xml
  core-design/src/main/res/drawable/ic_badge_info_arrow_16.png
  core-design/src/main/res/drawable/ic_calndar.xml
  core-design/src/main/res/drawable/ic_calndar_20.png
  core-design/src/main/res/drawable/ic_camera_30.png
  core-design/src/main/res/drawable/ic_delete_img_18.png
  core-design/src/main/res/drawable/ic_delete_review.xml
  core-design/src/main/res/drawable/ic_delete_review_16.png
  core-design/src/main/res/drawable/ic_edit.xml
  core-design/src/main/res/drawable/ic_edit_19.png
  core-design/src/main/res/drawable/ic_edit_badge.xml
  core-design/src/main/res/drawable/ic_img.xml
  core-design/src/main/res/drawable/ic_img_num_12.png
  core-design/src/main/res/drawable/ic_like_13.png
  core-design/src/main/res/drawable/ic_like_off.png
  core-design/src/main/res/drawable/ic_like_on.png
  core-design/src/main/res/drawable/ic_location_pin.xml
  core-design/src/main/res/drawable/ic_more.xml
  core-design/src/main/res/drawable/ic_more_32.png
  core-design/src/main/res/drawable/ic_place_num_13.png
  core-design/src/main/res/drawable/ic_rank_down.xml
  core-design/src/main/res/drawable/ic_rank_down_12.png
  core-design/src/main/res/drawable/ic_rank_question.xml
  core-design/src/main/res/drawable/ic_rank_question_15.png
  core-design/src/main/res/drawable/ic_rank_up.xml
  core-design/src/main/res/drawable/ic_rank_up_12.png
  core-design/src/main/res/drawable/ic_search.xml
  core-design/src/main/res/drawable/ic_search_32.png
  core-design/src/main/res/drawable/ic_star_13.png
  core-design/src/main/res/drawable/ic_star_gray_11.png
  core-design/src/main/res/drawable/ic_tem_badge_error.png
  core-design/src/main/res/drawable/ic_write_32.png
  core-design/src/main/res/drawable/img_badge_check.png
  core-design/src/main/res/drawable/img_location_pin.png
Labels: 리팩토링

#37 [ feature ] : 관심 목록 - Domain layer
  domain/src/main/java/com/ddd/ansayo/domain/handler/favorite/FavoriteCourseMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/favorite/FavoritePlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoriteCourseAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoriteCourseMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoriteCourseState.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoritePlaceAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoritePlaceMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/favorite/FavoritePlaceState.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/GetFavoriteCoursesUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/GetFavoritePlacesUseCase.kt
Labels: 기능개발

#41 [ feature ] : 관심 목록 - App Layer
  app/src/main/java/com/ddd/ansayo/base/BaseBindingAdapter.kt
  app/src/main/java/com/ddd/ansayo/extenstion/TextViewExt.kt
  app/src/main/java/com/ddd/ansayo/main/MainActivity.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteCourseAdapter.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteCourseFragment.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteListFragment.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteListFragmentAdapter.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoritePlaceAdapter.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoritePlaceFragment.kt
  app/src/main/res/layout/fragment_favorite_course.xml
  app/src/main/res/layout/fragment_favorite_list.xml
  app/src/main/res/layout/fragment_favorite_place.xml
  app/src/main/res/layout/item_favorite_course.xml
  app/src/main/res/layout/item_favorite_place.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable-hdpi/img_no_like_course.png
  core-design/src/main/res/drawable-hdpi/img_no_like_place.png
  core-design/src/main/res/drawable-xhdpi/img_no_like_course.png
  core-design/src/main/res/drawable-xhdpi/img_no_like_place.png
  core-design/src/main/res/drawable-xxhdpi/img_no_like_course.png
  core-design/src/main/res/drawable-xxhdpi/img_no_like_place.png
  core-design/src/main/res/drawable-xxxhdpi/img_no_like_course.png
  core-design/src/main/res/drawable-xxxhdpi/img_no_like_place.png
  core-design/src/main/res/drawable/background_tab_layout.xml
  core-design/src/main/res/drawable/img_no_like_course.png
  core-design/src/main/res/drawable/img_no_like_place.png
  core-design/src/main/res/drawable/selector_favorite.xml
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
Labels: 기능개발

#45 [ chore ] : build check시 local properties 파일 생성
  .github/workflows/build-check.yml
Labels: 환경설정

#44 [ feature ] : 네트워크 변경사항 적용
  data/src/main/java/com/ddd/ansayo/data/datasource/course/CourseRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/course/GetImageUploadUrlUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/DeleteFavoriteCourseUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/DeleteFavoritePlaceUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/GetFavoriteCoursesUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/GetFavoritePlacesUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/PostFavoriteCourseUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/favorite/PostFavoritePlaceUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/place/GetPlacesUseCase.kt
  gradle/libs.versions.toml
  local/src/main/java/com/ddd/ansayo/local/datasource/AuthLocalDataSourceImpl.kt
  remote/build.gradle.kts
  remote/src/main/java/com/ddd/ansayo/remote/datasource/CourseRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/NetworkModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/ServiceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/interceptor/AuthHeaderInterceptor.kt
  remote/src/main/java/com/ddd/ansayo/remote/util/ResponseUtil.kt
Labels: 기능개발

#46 [ feature ] : 장소 상세 - domain layer
  core-model/src/main/java/com/ddd/ansayo/core_model/place/PlaceInfoEntity.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/place/PlaceDetailMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/place/GetPlaceInfoUseCase.kt
Labels: 기능개발

#47 [ feature ] : 장소 상세 - Data layer
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#48 [ feature ] : 장소 상세 - Presentation layer
  domain/src/main/java/com/ddd/ansayo/domain/handler/place/PlaceDetailMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailState.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/place/PlaceDetailViewModel.kt
Labels: 기능개발

#50 [feature]: 검색화면 - DomainLayer 구현
  core-model/src/main/java/com/ddd/ansayo/core_model/search/SearchCourseEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/search/SearchPlaceEntity.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchCourseMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseState.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseSearchRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/search/GetSearchCoursesUseCase.kt
Labels: 기능개발

#49 [feature]: 소셜로그인 기능
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/GgecoApplication.kt
  app/src/main/java/com/ddd/ansayo/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  core-design/src/main/res/drawable/btn_login_kakao.png
  core-design/src/main/res/drawable/btn_login_naver.png
  core-design/src/main/res/drawable/ic_splash_ggeco.png
  core-model/src/main/java/com/ddd/ansayo/core_model/account/SocialProvider.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/account/SocialSignInParam.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/account/TokenInfo.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/account/TokenInfoResponse.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/AuthToken.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/TokenInfo.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/model/User.kt
  data/build.gradle.kts
  data/src/main/java/com/ddd/ansayo/data/datasource/account/AccountRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/auth/AuthRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/di/RepositoryModule.kt
  data/src/main/java/com/ddd/ansayo/data/di/UseCaseModule.kt
  data/src/main/java/com/ddd/ansayo/data/repository/account/AccountRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/account/KakaoUseCaseImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/KakaoUseCase.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/NaverUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/login/LoginMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/AuthRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/login/SocialLoginUseCase.kt
  domain/src/main/java/com/example/domain/account/AccountRepository.kt
  domain/src/main/java/com/example/domain/account/KakaoUseCase.kt
  domain/src/main/java/com/example/domain/account/SocialLoginUseCase.kt
  domain/src/main/java/com/example/domain/account/model/SocialSignUp.kt
  gradle/libs.versions.toml
  local/src/main/java/com/ddd/ansayo/local/preference/PreferenceUtil.kt
  local/src/main/java/com/ddd/ansayo/local/preference/UserPref.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/login/LoginViewModel.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/AuthRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/NetworkModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/ServiceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/interceptor/AuthHeaderInterceptor.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/LoginService.kt
Labels: 기능개발

#51 [feature]: 검색화면 DataLayer 구현
  core-model/src/main/java/com/ddd/ansayo/core_model/course/SearchCourseEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/SearchPlaceEntity.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/course/CourseRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/CourseRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/CourseService.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#52 [feature]: 검색화면 PresentationLay구현
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchCourseMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseState.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceState.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/course/CourseSearchViewModel.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/place/SearchPlaceViewModel.kt
Labels: 기능개발

#53 [feature]: 소셜로그인 기능
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/GgecoApplication.kt
  app/src/main/java/com/ddd/ansayo/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  core-design/src/main/res/drawable/btn_login_kakao.png
  core-design/src/main/res/drawable/btn_login_naver.png
  core-design/src/main/res/drawable/ic_splash_ggeco.png
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/AuthToken.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/TokenInfo.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/model/User.kt
  data/build.gradle.kts
  data/src/main/java/com/ddd/ansayo/data/AuthLocalDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/auth/AuthRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/di/RepositoryModule.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/KakaoUseCase.kt
  data/src/main/java/com/ddd/ansayo/data/repository/auth/NaverUseCase.kt
  domain/build.gradle.kts
  domain/src/main/java/com/ddd/ansayo/domain/handler/login/LoginMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/AuthRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/login/SocialLoginUseCase.kt
  gradle/libs.versions.toml
  local/build.gradle.kts
  local/src/main/java/com/ddd/ansayo/local/datasource/AuthLocalDataSourceImpl.kt
  local/src/main/java/com/ddd/ansayo/local/di/LocalDataSourceModule.kt
  local/src/main/java/com/ddd/ansayo/local/preference/PreferenceUtil.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/login/LoginViewModel.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/AuthRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/ServiceModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/interceptor/AuthHeaderInterceptor.kt
  remote/src/main/java/com/ddd/ansayo/remote/interceptor/TokenAuthenticator.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/LoginService.kt
  settings.gradle.kts
Labels: 기능개발

#55 [feature]: 검색화면 AppLayer 구현
  app/src/main/java/com/ddd/ansayo/search/SearchCourseAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchCourseFragment.kt
  app/src/main/java/com/ddd/ansayo/search/SearchListAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchListFragment.kt
  app/src/main/java/com/ddd/ansayo/search/SearchPlaceAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchPlaceFragment.kt
  app/src/main/res/layout/fragment_search_course.xml
  app/src/main/res/layout/fragment_search_list.xml
  app/src/main/res/layout/fragment_search_place.xml
  app/src/main/res/layout/item_search_course.xml
  app/src/main/res/layout/item_search_place.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable-hdpi/img_no_result.png
  core-design/src/main/res/drawable-xhdpi/img_no_result.png
  core-design/src/main/res/drawable-xxhdpi/img_no_result.png
  core-design/src/main/res/drawable-xxxhdpi/img_no_result.png
  core-design/src/main/res/drawable/bg_search_bar.xml
  core-design/src/main/res/drawable/img_no_result.png
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceMutation.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
Labels: 기능개발

#56 [feature] : 검색화면 기능
  app/src/main/java/com/ddd/ansayo/search/SearchCourseAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchCourseFragment.kt
  app/src/main/java/com/ddd/ansayo/search/SearchListAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchListFragment.kt
  app/src/main/java/com/ddd/ansayo/search/SearchPlaceAdapter.kt
  app/src/main/java/com/ddd/ansayo/search/SearchPlaceFragment.kt
  app/src/main/res/layout/fragment_search_course.xml
  app/src/main/res/layout/fragment_search_list.xml
  app/src/main/res/layout/fragment_search_place.xml
  app/src/main/res/layout/item_search_course.xml
  app/src/main/res/layout/item_search_place.xml
  app/src/main/res/values/strings.xml
  core-design/src/main/res/drawable-hdpi/img_no_result.png
  core-design/src/main/res/drawable-xhdpi/img_no_result.png
  core-design/src/main/res/drawable-xxhdpi/img_no_result.png
  core-design/src/main/res/drawable-xxxhdpi/img_no_result.png
  core-design/src/main/res/drawable/bg_search_bar.xml
  core-design/src/main/res/drawable/img_no_result.png
  core-model/src/main/java/com/ddd/ansayo/core_model/course/SearchCourseEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/SearchPlaceEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/search/SearchCourseEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/search/SearchPlaceEntity.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/course/CourseRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchCourseMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchCourseState.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/search/SearchPlaceState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseSearchRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/search/GetSearchCoursesUseCase.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/course/CourseSearchViewModel.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/place/SearchPlaceViewModel.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/CourseRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/CourseService.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#57 코스검색관련 에러 수정
  app/src/main/res/layout/fragment_search_course.xml
  core-model/src/main/java/com/ddd/ansayo/core_model/course/SearchCourseEntity.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/course/CourseRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchCourseMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseSearchRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/search/GetSearchCoursesUseCase.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/CourseRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/CourseService.kt
Labels: 버그수정

#58 [feature] 코스상세 DomainLayer 구현
  core-model/src/main/java/com/ddd/ansayo/core_model/course/CourseInfo.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/course/PlacePhoto.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/course/PlaceReview.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/course/CourseRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/course/CourseInfoHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/course/GetCourseInfoUseCase.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/CourseRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/CourseService.kt
Labels: 기능개발

#59 [ feature ] : 장소 상세
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/common/CourseViewHolder.kt
  app/src/main/java/com/ddd/ansayo/main/record/MyRecordAdapter.kt
  app/src/main/java/com/ddd/ansayo/place/PlaceDetailActivity.kt
  app/src/main/java/com/ddd/ansayo/place/PlaceDetailCourseAdapter.kt
  app/src/main/java/com/ddd/ansayo/place/PlaceDetailInfoAdapter.kt
  app/src/main/res/layout/activity_place_detail.xml
  app/src/main/res/layout/item_course.xml
  app/src/main/res/layout/item_place_detail_course_header.xml
  app/src/main/res/layout/item_place_detail_info.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  core-design/src/main/java/com/ddd/ansayo/core_design/util/RatingView.kt
  core-design/src/main/res/drawable/selector_main_text_color.xml
  core-design/src/main/res/layout/layout_rating_view.xml
  core-design/src/main/res/values/attrs.xml
  core-design/src/main/res/values/strings.xml
  core-model/src/main/java/com/ddd/ansayo/core_model/place/Place.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/PlaceInfoEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/Review.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/place/PlaceDetailMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/Course.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/place/PlaceDetailState.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/record/MyRecordMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/record/MyRecordState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/place/GetPlaceInfoUseCase.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/place/PlaceDetailViewModel.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#60 [ chore ] : 네트워크 로깅 라이브러리 추가
  gradle/libs.versions.toml
  remote/build.gradle.kts
  remote/src/main/java/com/ddd/ansayo/remote/di/NetworkModule.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/Qualifier.kt
  remote/src/main/java/com/ddd/ansayo/remote/di/ServiceModule.kt
Labels: 환경설정

#62 [feature] : 코스상세 PresentationLayer 구현
  domain/src/main/java/com/ddd/ansayo/domain/handler/course/CourseInfoMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoState.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/course/CourseInfoViewModel.kt
Labels: 기능개발

#63 [Feature] : 코스상세 AppLayer 구현
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoActivity.kt
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoAdapter.kt
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoBindingAdapter.kt
  app/src/main/res/layout/activity_course_info.xml
  app/src/main/res/layout/item_course_info_place.xml
  core-design/src/main/res/drawable-hdpi/btn_map_back.png
  core-design/src/main/res/drawable-xhdpi/btn_map_back.png
  core-design/src/main/res/drawable-xxhdpi/btn_map_back.png
  core-design/src/main/res/drawable-xxxhdpi/btn_map_back.png
  core-design/src/main/res/drawable/btn_map_back.png
Labels: 기능개발

#65 [feature] :코스상세 구현
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoActivity.kt
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoAdapter.kt
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoBindingAdapter.kt
  app/src/main/res/layout/activity_course_info.xml
  app/src/main/res/layout/item_course_info_place.xml
  core-design/src/main/res/drawable-hdpi/btn_map_back.png
  core-design/src/main/res/drawable-xhdpi/btn_map_back.png
  core-design/src/main/res/drawable-xxhdpi/btn_map_back.png
  core-design/src/main/res/drawable-xxxhdpi/btn_map_back.png
  core-design/src/main/res/drawable/btn_map_back.png
  domain/src/main/java/com/ddd/ansayo/domain/handler/course/CourseInfoMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoState.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/course/CourseInfoViewModel.kt
Labels: 기능개발

#66 [feature] : Naver Maps 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/GgecoApplication.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 환경설정

#64 [feature] : 소셜로그인 이동로직 구현
  app/src/main/java/com/ddd/ansayo/GgecoApplication.kt
  app/src/main/java/com/ddd/ansayo/login/LoginActivity.kt
  data/src/main/java/com/ddd/ansayo/data/AuthLocalDataSource.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/login/LoginMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginState.kt
  local/src/main/java/com/ddd/ansayo/local/datasource/AuthLocalDataSourceImpl.kt
  local/src/main/java/com/ddd/ansayo/local/preference/PreferenceUtil.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/login/LoginViewModel.kt
Labels: 기능개발

#67 [ refactor ] : 디자인 시스템 커스텀뷰 컴포넌트 수정
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoriteCourseFragment.kt
  app/src/main/java/com/ddd/ansayo/main/favorite/FavoritePlaceFragment.kt
  app/src/main/res/layout/fragment_favorite_course.xml
  app/src/main/res/layout/fragment_favorite_place.xml
  app/src/main/res/layout/item_course_write_footer.xml
  app/src/main/res/values/themes.xml
  core-design/src/main/java/com/ddd/ansayo/core_design/util/button/LabelPrimaryBottomMaxButton.kt
  core-design/src/main/java/com/ddd/ansayo/core_design/util/button/LabelPrimaryButton.kt
  core-design/src/main/java/com/ddd/ansayo/core_design/util/textfiled/TextField.kt
  core-design/src/main/java/com/ddd/ansayo/core_design/util/textfiled/TextFiledLong.kt
  core-design/src/main/java/com/ddd/ansayo/core_design/util/textfiled/TextFiledShort.kt
  core-design/src/main/res/drawable/button_label_secondary_error.xml
  core-design/src/main/res/layout/ds_button_primary_bottom_max.xml
  core-design/src/main/res/layout/ds_button_primary_default.xml
  core-design/src/main/res/layout/ds_text_filed_long.xml
  core-design/src/main/res/layout/ds_text_filed_short.xml
  core-design/src/main/res/values/attrs.xml
  core-design/src/main/res/values/strings.xml
Labels: 리팩토링

#68 [feat] : 토큰 저장로직 수정
  app/src/main/java/com/ddd/ansayo/login/LoginActivity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/auth/AuthToken.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/login/LoginMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/login/LoginMutation.kt
Labels: 기능개발

#69 [feature] : 코스상세 상단 지도영역 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/ansayo/course/info/CourseInfoActivity.kt
  app/src/main/java/com/ddd/ansayo/course/info/CourseMapBindingAdapter.kt
  app/src/main/java/com/ddd/ansayo/login/LoginActivity.kt
  app/src/main/res/layout/activity_course_info.xml
  app/src/main/res/values/dimens.xml
  core-design/src/main/res/drawable-hdpi/img_pin_no1.png
  core-design/src/main/res/drawable-hdpi/img_pin_no2.png
  core-design/src/main/res/drawable-hdpi/img_pin_no3.png
  core-design/src/main/res/drawable-hdpi/img_pin_no4.png
  core-design/src/main/res/drawable-xhdpi/img_pin_no1.png
  core-design/src/main/res/drawable-xhdpi/img_pin_no2.png
  core-design/src/main/res/drawable-xhdpi/img_pin_no3.png
  core-design/src/main/res/drawable-xhdpi/img_pin_no4.png
  core-design/src/main/res/drawable-xxhdpi/img_pin_no1.png
  core-design/src/main/res/drawable-xxhdpi/img_pin_no2.png
  core-design/src/main/res/drawable-xxhdpi/img_pin_no3.png
  core-design/src/main/res/drawable-xxhdpi/img_pin_no4.png
  core-design/src/main/res/drawable-xxxhdpi/img_pin_no1.png
  core-design/src/main/res/drawable-xxxhdpi/img_pin_no2.png
  core-design/src/main/res/drawable-xxxhdpi/img_pin_no3.png
  core-design/src/main/res/drawable-xxxhdpi/img_pin_no4.png
  core-design/src/main/res/drawable/img_pin_no1.png
  core-design/src/main/res/drawable/img_pin_no2.png
  core-design/src/main/res/drawable/img_pin_no3.png
  core-design/src/main/res/drawable/img_pin_no4.png
  core-model/src/main/java/com/ddd/ansayo/core_model/course/CourseInfo.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/course/CourseInfoMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/course/info/CourseInfoMutation.kt
  presentation/src/main/java/com/ddd/ansayo/presentation/viewmodel/Constant.kt
Labels: 기능개발

#70 [ feature ] : 코스 작성하기 - 장소 추가하기 UI 변경
  app/src/main/java/com/ddd/ansayo/place/PlaceDetailActivity.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceActivity.kt
  app/src/main/java/com/ddd/ansayo/place/SearchAddPlaceBindingAdapter.kt
  app/src/main/res/layout/activity_search_add_place.xml
  app/src/main/res/layout/item_search_add_place.xml
  core-design/src/main/res/layout/layout_rating_view.xml
  core-model/src/main/java/com/ddd/ansayo/core_model/place/AddPlaceInfoDto.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/place/Place.kt
  data/src/main/java/com/ddd/ansayo/data/datasource/place/PlaceRemoteDataSource.kt
  data/src/main/java/com/ddd/ansayo/data/repository/place/PlaceRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/place/SearchAddPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/search/SearchPlaceMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/PlaceRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/place/GetPlacesUseCase.kt
  remote/src/main/java/com/ddd/ansayo/remote/datasource/PlaceRemoteDataSourceImpl.kt
  remote/src/main/java/com/ddd/ansayo/remote/service/PlaceService.kt
Labels: 기능개발

#71 [feature]: 홈화면 DomainLayer 구현
  core-model/src/main/java/com/ddd/ansayo/core_model/badge/Badge.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/badge/BadgeEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/course/PopularCourseEntity.kt
  core-model/src/main/java/com/ddd/ansayo/core_model/course/RecentCourseEntity.kt
  data/src/main/java/com/ddd/ansayo/data/repository/course/CourseRepositoryImpl.kt
  domain/src/main/java/com/ddd/ansayo/domain/handler/home/HomeMutationHandler.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/home/HomeAction.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/home/HomeMutation.kt
  domain/src/main/java/com/ddd/ansayo/domain/model/home/HomeState.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/BadgeRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/repository/CourseRepository.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/badge/GetBadgeUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/course/GetPopularCourseUseCase.kt
  domain/src/main/java/com/ddd/ansayo/domain/usecase/course/GetRecentCourseUseCase.kt
Labels: 기능개발
